run:
  timeout: 2m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go|step_definitions/.*\.go
      linters:
        - errcheck