version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: movies-mcp-test-db
    environment:
      POSTGRES_DB: movies_mcp_test
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_password
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movies_user -d movies_mcp_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: