run:
  timeout: 2m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: validator_test\.go
      text: "Error return value of.*Validate.*is not checked"
      linters:
        - errcheck
    - path: transaction_manager\.go
      text: "Error return value of.*Rollback.*is not checked"
      linters:
        - errcheck