name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  GO_VERSION: '1.24.4'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: movies_mcp_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: movies_mcp_test
      DB_SSLMODE: disable
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-
            
      - name: Install dependencies
        run: |
          cd mcp-server && go mod download
          cd ../godog-server && go mod download
          cd ../shared-mcp && go mod download
          
      - name: Generate version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="$(git describe --tags --always --dirty)-$(date +%Y%m%d%H%M%S)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"
          
      - name: Build MCP server
        working-directory: mcp-server
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
            -ldflags="-w -s -X 'main.Version=${{ steps.version.outputs.version }}' -X 'main.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" \
            -o build/movies-server cmd/server/main.go
            
      - name: Run comprehensive tests
        run: |
          # Test shared components
          cd shared-mcp && go test -v -race -coverprofile=coverage.out ./...
          
          # Test MCP server with migrations
          cd ../mcp-server
          ./build/movies-server -migrate-only
          go test -v -race -coverprofile=coverage.out ./...
          go test -v -tags=integration ./tests/integration/...
          
          # Test ATDD scenarios
          cd ../godog-server
          go test -v -timeout=5m
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./mcp-server
          file: ./mcp-server/Dockerfile.production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
            BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
          format: spdx-json
          output-file: sbom.spdx.json
          
      - name: Scan image for vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
          fail-build: false
          severity-cutoff: high
          
      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif

  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment: staging
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to staging
        env:
          IMAGE_TAG: ${{ needs.build-and-test.outputs.image-tag }}
          VERSION: ${{ needs.build-and-test.outputs.version }}
        run: |
          echo "Deploying version $VERSION to staging environment"
          echo "Image: $IMAGE_TAG"
          
          # Here you would typically:
          # 1. Update Kubernetes manifests
          # 2. Deploy to staging cluster
          # 3. Run smoke tests
          # 4. Update service discovery
          
          # Example deployment commands:
          # kubectl set image deployment/movies-mcp-server movies-mcp-server=$IMAGE_TAG
          # kubectl rollout status deployment/movies-mcp-server
          
      - name: Run smoke tests
        env:
          STAGING_URL: ${{ vars.STAGING_URL }}
        run: |
          echo "Running smoke tests against staging environment: $STAGING_URL"
          
          # Wait for deployment to be ready
          sleep 30
          
          # Basic health check
          curl -f "$STAGING_URL/health" || exit 1
          
          # MCP protocol test
          echo '{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"ci-test","version":"1.0.0"}}}' | \
            curl -X POST -H "Content-Type: application/json" -d @- "$STAGING_URL" || exit 1
            
      - name: Create deployment record
        run: |
          echo "Deployment successful to staging"
          echo "Version: ${{ needs.build-and-test.outputs.version }}"
          echo "Image: ${{ needs.build-and-test.outputs.image-tag }}"
          echo "Digest: ${{ needs.build-and-test.outputs.image-digest }}"

  deploy-production:
    needs: [build-and-test, deploy-staging]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to production
        env:
          IMAGE_TAG: ${{ needs.build-and-test.outputs.image-tag }}
          VERSION: ${{ needs.build-and-test.outputs.version }}
        run: |
          echo "Deploying version $VERSION to production environment"
          echo "Image: $IMAGE_TAG"
          
          # Production deployment with blue-green strategy:
          # 1. Deploy to blue environment
          # 2. Run comprehensive tests
          # 3. Switch traffic to blue
          # 4. Monitor metrics
          # 5. Keep green as fallback
          
      - name: Run production tests
        env:
          PRODUCTION_URL: ${{ vars.PRODUCTION_URL }}
        run: |
          echo "Running production verification tests"
          
          # Comprehensive health checks
          curl -f "$PRODUCTION_URL/health" || exit 1
          curl -f "$PRODUCTION_URL/metrics" || exit 1
          
          # MCP protocol verification
          echo '{"jsonrpc":"2.0","id":"1","method":"tools/list"}' | \
            curl -X POST -H "Content-Type: application/json" -d @- "$PRODUCTION_URL" || exit 1
            
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            This release includes:
            - MCP Server version ${{ needs.build-and-test.outputs.version }}
            - Container image: ${{ needs.build-and-test.outputs.image-tag }}
            - Image digest: ${{ needs.build-and-test.outputs.image-digest }}
            
            ## Deployment Information
            
            - **Staging**: Automatically deployed ✅
            - **Production**: Deployed with this release ✅
            
            ## Verification
            
            All tests passed including:
            - Unit tests
            - Integration tests  
            - ATDD scenarios
            - Security scans
            - Smoke tests
            
          draft: false
          prerelease: false

  cleanup:
    needs: [build-and-test, deploy-production]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Clean up old images
        run: |
          echo "Cleaning up old container images"
          # This would typically clean up old images from the registry
          # to manage storage costs and keep only recent versions